name: make_it_exist
description: "Make It Exist - Weekend Build Service for AIM Students"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.4.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # SSO
  google_sign_in: ^6.2.1
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Utils
  intl: any
  url_launcher: ^6.2.2
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Form
  flutter_form_builder: ^10.3.0
  form_builder_validators: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
